### ISSUE TITLE
Feature: GitHub Action to Check Last Update of Source Code Repositories

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/inat_toolbox#1]
### Overview

We maintain a list of iNaturalist-related tools in our `README.md`, many of which include GitHub repositories as "source code" links. It would be helpful to track when these projects were last updated to keep the showcase relevant and active.

### ✅ Goals

- Extract all GitHub repository links listed as source code in the `README.md`.
- Query the GitHub API to retrieve the latest `pushed_at` timestamp for each repository.
- Output this information in the GitHub Actions logs (and optionally to a file).

---

### 🛠️ Proposed Solution

Add a GitHub Actions workflow with a Python script that:

1. **Parses the README**
   - Finds all GitHub repo links using a regex.
2. **Queries GitHub API**
   - Requests the last update date via `https://api.github.com/repos/{owner}/{repo}`.
3. **Outputs**
   - Logs the update times for each repository.
   - Optionally outputs to a file or comment on a PR.

---

### 📁 Workflow File: `.github/workflows/check-updates.yml`

```yaml
name: Check GitHub Repo Update Dates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1' # Weekly, Monday at noon UTC

jobs:
  check-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Check last updated times
        run: python .github/scripts/check_updates.py
```

---

### 🐍 Script File: `.github/scripts/check_updates.py`

```python
import re
import requests
from pathlib import Path

README_PATH = Path("README.md")
GITHUB_API = "https://api.github.com/repos/"
TOKEN = ""  # Optional: use GitHub token via secrets if needed

headers = {"Authorization": f"token {TOKEN}"} if TOKEN else {}

def extract_github_urls(text):
    return re.findall(r'https://github\.com/[\w\-]+/[\w\-]+', text)

def get_last_update(repo_url):
    slug = "/".join(repo_url.split("/")[-2:])
    resp = requests.get(GITHUB_API + slug, headers=headers)
    if resp.status_code == 200:
        data = resp.json()
        return slug, data["pushed_at"]
    else:
        return slug, f"Error: {resp.status_code}"

def main():
    content = README_PATH.read_text()
    urls = set(extract_github_urls(content))
    for url in sorted(urls):
        repo, updated = get_last_update(url)
        print(f"{repo}: {updated}")

if __name__ == "__main__":
    main()
```

---

### 🔐 Optional Enhancements

- Add a GitHub token as a secret (`GH_TOKEN`) to increase the API rate limit.
- Output results to a file and track in the repository.
- Automatically open issues or PRs if a repo hasn’t been updated in a long time.
