### ISSUE TITLE
Feature: Build a GitHub Pages Site for the Showcase

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/inat_toolbox#2]
### 🧭 Overview

We want to build a GitHub Pages site that presents our list of iNaturalist API showcase projects in a structured and visually friendly way. This would make it easier for users to browse, filter, and explore tools.

#### 1. **Store Showcase Data in a Structured Format**

Move the list from the `README.md` into a structured format like **YAML** or **JSON** to support automated updates and easier site generation.

**Example (YAML):**

```yaml
- title: Learn the Land
  url: https://learnthe.land/
  author:
    name: Corey Farwell
    profile: https://github.com/frewsxcv
  description: Flashcard web app for naturalists powered by iNaturalist...
  category: Learning
  source_code: https://github.com/frewsxcv/learnthe.land
  last_updated: 2024-12-30
```

#### 2. **Set Up GitHub Pages**

**Option A: Jekyll (native GitHub Pages support)**  
- Store data in `_data/showcase.yml`
- Use Liquid templates to generate pages from the YAML

**Option B: Static Frontend (React, Eleventy, etc.)**
- Use JSON/YAML in a static site generator
- Build and deploy using GitHub Actions

#### 3. **Integrate with GitHub Action**

Update the existing `check_updates.py` script to:
- Read the data file
- Query GitHub for `pushed_at` info
- Update the `last_updated` field for each item
- Commit changes if updates are found

#### 4. **Optional Enhancements**
- Sort/filter by category, last updated, author, etc.
- Add full-text search
- Visual indicators for outdated/inactive tools

---

### ✅ Benefits

- Clean, user-friendly interface
- Easier browsing and discovery
- Maintains relevance with automatic updates
