### ISSUE TITLE
Feature Proposal: Add Tags to Items in the Showcase

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/inat_toolbox#3]
### ✨ Summary

Currently, showcase items are organized into broad **categories** like "Learning", "Games", or "Utilities and data processing". To allow for more granular filtering and discoverability, we should introduce **tags** for each item (e.g. `mobile`, `discord`, `chrome-extension`, `offline`, `field-work`, `AI`).

### ✅ Benefits

- More flexible filtering beyond rigid categories
- Enables users to explore related tools across categories (e.g. all Discord bots or all tools using computer vision)
- Supports future enhancements like search, tag clouds, or advanced filters on a GitHub Pages site

### 🔧 Proposed Approach

- Add a `tags` field to each item in the data structure (`showcase.yml` or JSON file)

**Example:**

```yaml
- title: Dronefly
  url: https://example.com
  author:
    name: iNaturalist Discord Community
    profile: https://github.com/dronefly-garden
  description: A Discord bot that gives users access to iNaturalist
  category: Utilities and data processing
  source_code: https://github.com/dronefly-garden/dronefly
  tags: [discord, bot, chat, automation]
```

- Update the GitHub Pages templates to optionally display tags
- (Optional) Add filtering UI in the site frontend

### 💬 Discussion Points

- What initial tag taxonomy should we use?
- Should we allow freeform tags or use a predefined set?
- Should tags replace or supplement categories (current proposal: supplement)?
